### PR TITLE
Solar cleanup

### PR DESCRIPTION
**Pull request by spco**
Address issues with solar calculations. In particular, split `eqtime` calculation into a new function, simplify the `currentFracHour`, and correct the calculation of theta for a zero-based day-of-the-year.

### CODE REVIEW

**Comment by spco** [comment]
Now, `EQT` matches the reference calculations exactly, apart from a similar difference at midnight as seen with `DEC`. Both are now fine - I don't think the choice of `DEC` at exactly midnight is anything to worry about.

@rs028: My `LHA` values are still a little out, but this is a position-dependent value. What longitude are the reference values calculated for? I'm calculating for `lat=51.51, lon=0.13`, which could easily account for any discrepancy in my numbers, if you're calculating for 0 longitude. I can re-run with whatever longitude.

**Comment by rs028** [comment]
I agree about `EQT` and `DEC`. Does it also deals correctly with the Dec 31-Jan 1 transition?

I calculated the values for lat=51.51, long=0.13 and dates "01-03-14 00:00:00" to "01-03-16 00:00:00".
How much out is it?

**Comment by spco** [comment]
Yes, that transition works fine (apart form the midnight discrepancy as ususal).

Ok, looks like there's still something going on with `LHA`. We're a few percent out, but not a steady amount that I can see. There's something still to figure out about the differences.

**Comment by spco** [comment]
Based on the spreadsheets at https://www.esrl.noaa.gov/gmd/grad/solcalc/calcdetails.html, our calculations here are at least as accurate those in calculated.csv from your email. And I'm happy to say that I was slightly misreading my spreadsheet before - we get agreement to within 2% relative error everywhere apart from at the midday value - these have very small absolute values, so the relative error gets quite large. But the absolute error hovers around 0.007 which is very small. So I think this may be sufficient - we have hit the point where the differences in our choices of approximation are the biggest factor, rather than any calculation issues.

**Comment by rs028** [comment]
Excellent, great job!

**Comment by spco** [comment]
Fixes #305

**Pull request merged**
