### PR TITLE
Testing of dilute fix

### PR DESCRIPTION
**Pull request by spco**
My personal version of #408 for my testing and development purposes

### CODE REVIEW

**Comment by rs028** [comment]
TBH, I am not entirely sure constraining DILUTE is a needed feature. It won't hurt to have that possibility, but I can't imagine many cases were it's needed. So, if it is too much work, I think you can leave it :)

**Comment by spco** [comment]
Seems like my PR was breaking the tests even before I removed the hard-coding, so I'm trying to understand that...

**Comment by spco** [comment]
@rs028 - so it turns out the only issue was that the `full` test has a non-zero DILUTE value, which seems to cause a stall in the solve (and would obviously also have a different solution now that DILUTE is being treated correctly). It may be that we need to change that test to something that actually solves correctly - I've only managed to get this PR to complete by skipping the `full` test.

**Comment by rs028** [comment]
Meaning this has nothing to do with constraining or not, I guess.
Obviously the full test results will need to be updated. But this means that the model cannot complete the run when it is using the dilute value?

**Comment by spco** [comment]
Yeah - up until now the dilute value hasn't been used, so we're just changing the solution (and evidently that hits a solvability issue). I think that's purely a function of this specific model (`full`), so we may just be able to tweak it until it solves. Perhaps the dilution factor (about 1e-6) is too small - that could well cause numerical issues

**Comment by rs028** [comment]
I think that may well be the case

**Comment by rs028** [comment]
I think we are done with this, no? `DILUTE` cannot be constrained, but that is fine. Very few applications require that and we know how to implement that, if needed.

**Comment by spco** [comment]
It would seem so from my perspective!

**Comment by rs028** [comment]
@spco this could be closed, or do you need it for further testing?

**Comment by spco** [comment]
Thanks all!

**Pull request closed without merging**
