### PR TITLE
Print version at top of output

### PR DESCRIPTION
**Pull request by spco**
This is the simplest way to address #10. It just requires us to remember to update this to 'v1.1' as the last thing before we release version 1.1. Thoughts?

### CODE REVIEW

**Comment by spco** [comment]
Sorted. Are you happy if I merge this?

**Comment by rs028** [comment]
This is probably the easiest way. It occurs to me whether the whole printout should be redirected to a log file. It gets pretty big for a long model run. But maybe it's better to do it in other PR.

**Comment by spco** [comment]
I think I'd prefer to leave that to the user to direct with `> atchem2.out` or similar, but I'm not too fussy. That could also be a command line option -`-o atchem2.out` etc.

**Comment by rs028** [comment]
All right. Let's merge this.

**Pull request merged**
