### PR TITLE
Fix .fac file tails.

### PR DESCRIPTION
**Pull request by spco**

### CODE REVIEW

**Comment by rs028** [comment]
Yes I do. But did you change anything? It seems you only removed the empty lines in the fac files.

**Comment by spco** [comment]
Sorry, to be clear, are you confirming that you do see differences afterwards? Is this on files you haven't touched, or is it only on those that have been opened in a text editor? Just trying to work out what's going on - I think it's all in the line endings being used by the OS.

**Comment by rs028** [comment]
Yes I cloned this branch, changed the `Makefile`, run `tools/build.sh tools/mcm_example.fac` then `.\atchem2`. This is what I get.

```
diff --git a/tools/mcm_example.fac b/tools/mcm_example.fac
index f798b25..de84dac 100644
--- a/tools/mcm_example.fac
+++ b/tools/mcm_example.fac
@@ -253,4 +253,4 @@ RO2 = CH3O2 ;
 % 2.85D-12*EXP(-345/TEMP) : CH3OH + OH = HO2 + HCHO ;
 *;
 * End of Subset.  No. of Species = 30, No. of Reactions = 71 ;
-   
+     
```

**Comment by spco** [comment]
Ah. Is this the only one? I forgot to update `tools/mcm_example.fac`. If you run `make tests` does it affect the test `.fac` files?

**Comment by spco** [comment]
Nor me, entirely - line endings are a right pain!

**Pull request merged**
