### PR TITLE
Start version 1.3-dev

### PR DESCRIPTION
**Pull request by rs028**
(re)start version `1.3-dev` and update the manual.

### CODE REVIEW

**Comment by rs028** [comment]
@spco I will leave this open for a bit, in case there are other changes to make to the manual.

**Comment by rs028** [comment]
@spco what is happening with the unit tests?

**Comment by rs028** [comment]
I realize I had forgotten to push all the changes and merge this!
@spco, is the failure of unit tests on codecov a worry?

**Comment by spco** [comment]
Sorry for the slow response - no, the codecov is broken so ignore it for now!

**Pull request merged**
