### PR TITLE
Pre-release v1.2

### PR DESCRIPTION
**Pull request by rs028**
This PR includes a few small improvements and bug fixes before the release of 1.2

### CODE REVIEW

**Comment by rs028** [comment]
Is this all that is needed to solve #407?

**Comment by rs028** [comment]
Yes I figure alI the fortran files. I started with one to check first that I was not missing something.

**Comment by rs028** [comment]
The script `mech_converter.py` adds `implicit none` to `mechanism.f90` should this be removed as well?

**Comment by spco** [comment]
We should leave it - it could be moved out of `update_p`, and into the module `mechanism_mod`, but up to you whether you move it or leave it where it is.

**Comment by rs028** [comment]
Does this solve #407 completely?

**Comment by spco** [comment]
From what I can grep, that looks right :)

**Comment by rs028** [comment]
@spco I would like to solve at least #413, if possible, before merging this. I imagine you are probably swamped with your stuff these days, but would you be able to point me in the right direction?

**Comment by rs028** [comment]
It seems I was overly optimistic in thinking I might have more time on my hands during the lockdown :) so I think this is a good point to stop and freeze v1.2.

The build still fails on macOS, but this time with an error message:
```
/usr/local/Cellar/gcc@4.9/4.9.4_1/bin/gfortran-4.9  selected as fortran compiler, but this is not a valid filename.
Example usage: ./install_cvode.sh /path/to/install/directory /path/to/fortran/compiler
The command "if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then ./tools/install/install_cvode.sh $PWD /usr/local/Cellar/gcc@4.9/4.9.4_1/bin/gfortran-4.9 ; fi" failed and exited with 1 during .
```

If this is a problem at their end, I will merge it anyways (it is fine on linux).

**Comment by spco** [comment]
Seems we also have a problem to fix - I've cleared the cache and the install of libffi is still failing. It's probably homebrew changing a setting, or Travis changing something internal with their image. Will need to do some digging as to why that is, but not now - I don't see any reason for it to delay v1.2 either.

**Pull request merged**
