### PR TITLE
Test code coverage

### PR DESCRIPTION
**Pull request by rs028**
This is simply to test that code coverage works as intended. (First need to merge PR #501).

### CODE REVIEW

**Comment by rs028** [comment]
After resetting Codecov, with one unit test the reported coverage is 3.16%, with 100% coverage in the `unit_tests` directory and 1.12% in the `src/` directory (correctly identifies the `argparse.f90` as affected by the tests).

**Comment by rs028** [comment]
Adding one model test increases coverage to 39.38% with 100% coverage in the `tests/unit_tests/` directory and 38.22% in the `src/` directory.

**Comment by rs028** [comment]
With another unit test, total coverage increases to 41.40%.
In particulare `atmosphereFunctions.f90` coverage goes from 29.63% to 61.54%.

**Comment by rs028** [comment]
Adding all unit tests increases total coverage to 50.93%

**Comment by rs028** [comment]
@spco @JamesAllsopp I think this is working (see my notes above). Total coverage is now 52%, which is lower than it was, but I think this reflects the fact that it is now calculated properly. Any comments before I merge? (can one of you approve the PR, when you have a minute? thanks).

@JamesAllsopp Can you check you are happy with the acknowledgements in the `Credits.tex` file?

**Review by spco — APPROVED** [review]

**Pull request merged**
